project_id = "iejeszcdlpfgoufcjumj"

[functions.kubectl]
verify_jwt = true

[functions.monitor-clusters]
verify_jwt = false

[functions.intelligent-analysis]
verify_jwt = false

[functions.prometheus-monitor]
verify_jwt = false

[functions.slack-integration]
verify_jwt = true